-- MuzicMania Mega-Migration (v2.1)
-- Combinación de esquemas iniciales y evolución del sistema.
-- Este script es IDEMPOTENTE (se puede correr varias veces sin errores).

-- 0. ASEGURAR QUE LAS TABLAS BASE EXISTEN
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username TEXT UNIQUE,
  display_name TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- 1. CORRECCIÓN DE SEGURIDAD: handle_new_user
-- Evita "Search Path Mutable" y advertencias de SECURITY DEFINER
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (
    id, 
    username, 
    display_name, 
    avatar_url,
    country,
    birth_date,
    first_name,
    last_name,
    phone
  )
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    COALESCE(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'country',
    (new.raw_user_meta_data->>'birth_date')::date,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    new.raw_user_meta_data->>'phone'
  );
  RETURN new;
END;
$$;

-- Revocar ejecución pública para mayor seguridad
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM authenticated;

-- Asegurar el trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 2. EXPANSIÓN DE LA TABLA PROFILES
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS display_name TEXT,
ADD COLUMN IF NOT EXISTS country TEXT,
ADD COLUMN IF NOT EXISTS birth_date DATE,
ADD COLUMN IF NOT EXISTS first_name TEXT,
ADD COLUMN IF NOT EXISTS last_name TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS badges TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS status_message TEXT,
ADD COLUMN IF NOT EXISTS high_score BIGINT DEFAULT 0;

-- Habilitar RLS para perfiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Re-crear políticas de perfiles (Drop first to avoid "already exists")
DROP POLICY IF EXISTS "Los usuarios pueden ver cualquier perfil." ON public.profiles;
CREATE POLICY "Los usuarios pueden ver cualquier perfil." ON public.profiles
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Los usuarios pueden editar su propio perfil." ON public.profiles;
CREATE POLICY "Los usuarios pueden editar su propio perfil." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- 3. TABLA DE LEADERBOARDS / SCORES
CREATE TABLE IF NOT EXISTS public.scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  track_id TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  accuracy DECIMAL DEFAULT 0,
  max_combo INTEGER DEFAULT 0,
  difficulty TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Cualquiera puede ver la tabla de clasificación." ON public.scores;
CREATE POLICY "Cualquiera puede ver la tabla de clasificación." ON public.scores
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Solo usuarios autenticados pueden subir puntuaciones." ON public.scores;
CREATE POLICY "Solo usuarios autenticados pueden subir puntuaciones." ON public.scores
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 4. TABLA DE LIKES
CREATE TABLE IF NOT EXISTS public.likes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  track_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, track_id)
);

ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Likes are viewable by everyone" ON public.likes;
CREATE POLICY "Likes are viewable by everyone" ON public.likes
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can manage their own likes" ON public.likes;
CREATE POLICY "Users can manage their own likes" ON public.likes
  FOR ALL USING (auth.uid() = user_id);

-- 5. TABLA DE TRACK STATS
CREATE TABLE IF NOT EXISTS public.track_stats (
  track_id TEXT PRIMARY KEY,
  play_count BIGINT DEFAULT 0,
  like_count BIGINT DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.track_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Track stats are viewable by everyone" ON public.track_stats;
CREATE POLICY "Track stats are viewable by everyone" ON public.track_stats
  FOR SELECT USING (true);

-- 6. FUNCIÓN PARA ACTUALIZAR CONTEO DE LIKES
CREATE OR REPLACE FUNCTION public.update_track_like_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    INSERT INTO public.track_stats (track_id, like_count)
    VALUES (NEW.track_id, 1)
    ON CONFLICT (track_id) 
    DO UPDATE SET like_count = public.track_stats.like_count + 1, updated_at = now();
    RETURN NEW;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.track_stats 
    SET like_count = like_count - 1, updated_at = now()
    WHERE track_id = OLD.track_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS on_like_change ON public.likes;
CREATE TRIGGER on_like_change
  AFTER INSERT OR DELETE ON public.likes
  FOR EACH ROW EXECUTE FUNCTION public.update_track_like_count();

-- Revocar ejecución pública para la función de likes (Seguridad)
REVOKE EXECUTE ON FUNCTION public.update_track_like_count() FROM public;
REVOKE EXECUTE ON FUNCTION public.update_track_like_count() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_track_like_count() FROM authenticated;

-- 7. TABLA DE TICKETS (Soporte) - ASEGURAR EXISTENCIA
CREATE TABLE IF NOT EXISTS public.tickets (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  subject TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT DEFAULT 'open',
  priority TEXT DEFAULT 'normal',
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios pueden ver sus propios tickets" ON public.tickets;
CREATE POLICY "Usuarios pueden ver sus propios tickets" ON public.tickets
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios pueden crear tickets" ON public.tickets;
CREATE POLICY "Usuarios pueden crear tickets" ON public.tickets
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins can view all tickets" ON public.tickets;
CREATE POLICY "Admins can view all tickets" ON public.tickets
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = true
    )
  );

-- 8. LIMPIEZA DE CUENTAS DE PRUEBA (Instrucciones)
-- Nota: La eliminación de usuarios de Auth debe hacerse manualmente en el panel de Supabase 
-- o mediante la nueva DevConsole que te he creado usando `supabaseAdmin.auth.admin.deleteUser`.
