[package]
name = "muzicmania"
version = "2.0.0"
description = "MuzicMania 2.0 - Ecosistema Rítmico de Alto Rendimiento | Ciszu Network"
authors = ["Ciszu Network <fplayersoffcial@gmail.com>"]
license = "Proprietary"
repository = "https://github.com/CiszukoAntony/MuzicMania"
homepage = "https://muzicmania.vercel.app"
edition = "2021"
rust-version = "1.77.2"

[profile.release]
panic = "abort"
opt-level = "s"
strip = "symbols"
codegen-units = 1

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
