export interface DocMetadata {
  title: string;
  description: string;
  icon: string;
  category: 'info' | 'support' | 'legal' | 'development' | 'ia';
  lastUpdate: string;
  author: string;
  version: string;
}

export const DOCS_METADATA: Record<string, DocMetadata> = {
  ABOUT: {
    title: 'Sobre el Bot',
    description: 'La visión, valores y características de CiszuBot.',
    icon: 'bot',
    category: 'info',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  ACTA: {
    title: 'Acta de Constitución',
    description: 'Documento oficial de formalización y bases del proyecto.',
    icon: 'shield',
    category: 'legal',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  CHANGELOG: {
    title: 'Historial de Cambios',
    description: 'Registro detallado de actualizaciones y nuevas características.',
    icon: 'history',
    category: 'development',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  CONTACT: {
    title: 'Contacto y Redes',
    description: 'Canales oficiales de soporte y redes sociales.',
    icon: 'mail',
    category: 'development',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  CREDITS: {
    title: 'Créditos',
    description: 'El equipo y las mentes detrás del bot.',
    icon: 'star',
    category: 'info',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  FAQ: {
    title: 'Preguntas Frecuentes',
    description: 'Respuestas rápidas a las dudas más comunes.',
    icon: 'helpCircle',
    category: 'support',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  FORUM: {
    title: 'Foro de Comunidad',
    description: 'Protocolos de interacción y debate en el foro oficial.',
    icon: 'messageSquare',
    category: 'info',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  GUIDELINES: {
    title: 'Directrices de Uso',
    description: 'Guía técnica para optimizar tu experiencia con el bot.',
    icon: 'compass',
    category: 'support',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  HELP: {
    title: 'Centro de Ayuda',
    description: 'Manuales y tutoriales para resolver problemas técnicos.',
    icon: 'lifeBuoy',
    category: 'support',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  INFORMATION: {
    title: 'Información Técnica',
    description: 'Detalles profundos sobre la arquitectura del bot.',
    icon: 'terminal',
    category: 'info',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  LEADERBOARD: {
    title: 'Tablas de Clasificación',
    description: 'Reglas de puntuación y algoritmos del ranking.',
    icon: 'trophy',
    category: 'info',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  LIBRARY: {
    title: 'Librería de Recursos',
    description: 'Gestión de assets multimedia y licencias de contenido.',
    icon: 'bookOpen',
    category: 'info',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  LICENSE: {
    title: 'Licencia',
    description: 'Términos legales de uso del software y código abierto.',
    icon: 'fileText',
    category: 'legal',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  POLICY: {
    title: 'Privacidad',
    description: 'Cómo tratamos tus datos y protegemos tu seguridad.',
    icon: 'shield',
    category: 'legal',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  RULES: {
    title: 'Reglas de Comunidad',
    description: 'Normas de conducta y fair play en el servidor.',
    icon: 'list',
    category: 'legal',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  SECURITY: {
    title: 'Seguridad',
    description: 'Protocolos de protección y reporte de vulnerabilidades.',
    icon: 'lock',
    category: 'legal',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  STATS: {
    title: 'Estadísticas del Bot',
    description: 'Interpretación de métricas y rendimiento del bot.',
    icon: 'barChart',
    category: 'info',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  TERMS_AND_CONDITIONS: {
    title: 'Términos y Condiciones',
    description: 'El contrato legal entre tú y CiszuBot.',
    icon: 'bookOpen',
    category: 'legal',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  TEAM: {
    title: 'Nuestro Equipo',
    description: 'Conoce a los creadores y colaboradores.',
    icon: 'users',
    category: 'info',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  SUPPORT: {
    title: 'Soporte Técnico',
    description: 'Canales directos para resolver incidencias.',
    icon: 'activity',
    category: 'support',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
  DOCUMENTATION: {
    title: 'Sobre la Documentación',
    description: 'Metadatos y estructura de este portal.',
    icon: 'book',
    category: 'info',
    lastUpdate: '2026-09-18',
    author: 'Ciszuko Antony',
    version: '2.5.5',
  },
};
