name: Deploy Ciszuko Antony Website

on:
    push:
        branches: [main, master]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ${{ vars.PREFERRED_RUNNER || 'self-hosted' }}
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  dest: ~/setup-pnpm-${{ runner.name }}
            - uses: actions/setup-node@v4
              with:
                  cache: pnpm
            - name: Install Vercel CLI
              run: pnpm add -g vercel
            - name: Link Vercel Project
              run: vercel link --yes --project ciszukoantonypage --token=${{ secrets.VERCEL_TOKEN }}
              working-directory: .
            - name: Deploy to Vercel
              run: vercel --prod --yes --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
              working-directory: .
